# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models


class DistritosModel(models.Model):    
    fid = models.FloatField()
    nom_ccpp = models.CharField(max_length=254,null=True)
    idmanzana = models.CharField(max_length=254,null=True)
    id_manzana = models.CharField(max_length=254,null=True)
    departamen = models.CharField(max_length=254,null=True)
    provincia = models.CharField(max_length=254,null=True)
    distrito = models.CharField(max_length=254,null=True)
    hombre = models.FloatField(null=True)
    mujer = models.FloatField(null=True)
    pob_total = models.IntegerField(null=True)
    ubigeo = models.CharField(max_length=10,null=True)
    f0_a_14 = models.FloatField(null=True)
    f15_a_29 = models.FloatField(null=True)
    f60_a_mas = models.FloatField(null=True)
    f30_a_59 = models.FloatField(null=True)
    pob_nbi = models.FloatField(null=True)
    pob_midis = models.FloatField(null=True)
    propor_nbi = models.FloatField(null=True)
    q_propnbi = models.CharField(max_length=10,null=True)
    p_propnbi = models.FloatField(null=True)
    area_ha = models.FloatField(null=True)
    dens_pob = models.CharField(max_length=254,null=True)
    q_pob60 = models.CharField(max_length=10,null=True)
    p_pob60 = models.FloatField(null=True)
    q_30_a_59 = models.CharField(max_length=10,null=True)
    p_30_a_59 = models.FloatField(null=True)
    q_densid = models.CharField(max_length=10,null=True)
    p_densid = models.FloatField(null=True)
    q_mcalor = models.CharField(max_length=10,null=True)
    p_mcalor = models.FloatField(null=True)
    q_mercado = models.CharField(max_length=10,null=True)
    p_mercado = models.FloatField(null=True)
    v_descen = models.FloatField(null=True)
    v_condic = models.FloatField(null=True)
    v_susc = models.FloatField(null=True)
    v_eexp = models.FloatField(null=True)
    v_riesgo = models.FloatField(null=True)
    n_riesgo = models.CharField(max_length=15,null=True)
    geom = models.MultiPolygonField(srid=4326,null=True)


